on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: build-action
        env:
          VITE_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          cd memurb
          npm install
          npm run build
      - name: ftp-action
        # You may pin to the exact commit or the version.
        # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          # FTP host
          host: ftp://31.170.160.198
          # FTP user
          user: u560911409.memurbe.com
          # FTP password
          password: ${{ secrets.ftp_password }}
          # Local directory
          localDir: memurb/build
